apiVersion: apps/v1
kind: Deployment
metadata:
  name: newspaper-deploy
spec:
  selector:
    matchLabels:
      app: newspaperservice
  template:
    metadata:
      labels:
        app: newspaperservice
    spec:
      containers:
        - name: newspaperservice
          image: dragoshomner/newspaperservice:latest
          resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: newspaper-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: newspaperservice
  ports:
  - name: newspaperservice
    protocol: TCP
    port: 80
    targetPort: 80