apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-deploy
spec:
  selector:
    matchLabels:
      app: subscriptionservice
  template:
    metadata:
      labels:
        app: subscriptionservice
    spec:
      containers:
        - name: subscriptionservice
          image: dragoshomner/subscriptionservice:latest
          resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: subscriptionservice
  ports:
  - name: subscriptionservice
    protocol: TCP
    port: 80
    targetPort: 80